### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by Hehomarco**

### CODE REVIEW

**Comment by metachris** [comment]
I don't think it's a good idea to copy all the code for each language; having the Python source codes just in English should be fine. The README perhaps, but even there I'm not sure since you have the additional maintenance overhead once things change in the English version, and developers are used to working with English docs anyway.

I suggest not to go the route suggested in this PR.

**Comment by Hehomarco** [comment]
Hey Metacris, i think its a good idea because i translated the Neo Docs to german and got lots of good feedback at reddit. I dont change the code himself i only change the comments and so on. And i think its not bad translated and sure not automatically. Lets Fabwa decide he also saw my german neo docs translation and he found that this are good. Really dont know what your problem is

**Comment by metachris** [comment]
No problem here, Just my 2c. Really didn't mean to offend you.

I'm not a fan of duplicating the whole codebase into multiple languages because that leads to a maintenance nightmare. 

About the language -- there's just lots of grammar errors, and it looks like automatic translations.

**Comment by Hehomarco** [comment]
Okay thats your 2c. Whatever i only dont like guys that come here and doesnt respect the effort others do. 
Lets someone decide that has something to decide. And i will take a look if i find your mentioned grammar errors. Thank you

**Comment by metachris** [comment]
Look, I value your efforts and really didn't want to offend you. I suppose it would be better to ask if this would be a good effort before just going to do it, else you also need to be prepared for critical feedback. This really is meant in a constructive spirit, and I hope you can take it as such.

**Comment by Hehomarco** [comment]
That is what i did, i talked to afong about it and he seems to be okay with that. Okay i take it as constructive feedback.

**Comment by Hehomarco** [comment]
Okay first of all sorry Metachris i didnt know you are involved in NEX. I felt offended in some way. I will work on a better grammar if you guys still belive its a good idea. I also change what canesin requested. But i dont want to waste my time if you guys think its not needed. Its a bit frustrating that afong said for translation i should ask him and Fabwa.

**Comment by canesin** [comment]
@Hehomarco @metachris is not involved in NEX.

**Comment by localhuman** [comment]
Thanks @Hehomarco for your work, and @metachris for the feedback.  I agree that copying the source code is not the approach we will want to take.  
We will add in a sphinx docs build, which is much better suited to handle internationalization for documentation.

**Pull request closed without merging**
